# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ROOM" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"roomName" VARCHAR NOT NULL,"creatorId" BIGINT,"permission" VARCHAR NOT NULL,"dataType" VARCHAR NOT NULL,"dateFrom" DATE NOT NULL,"dateTo" DATE NOT NULL,"maxValue" INTEGER NOT NULL,"labels" VARCHAR NOT NULL);
create table "SURVEY" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"roomId" BIGINT NOT NULL,"userId" BIGINT NOT NULL,"data" VARCHAR NOT NULL);
create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"password" VARCHAR NOT NULL);
create unique index "uniqe" on "USER" ("name");
alter table "SURVEY" add constraint "roomFk" foreign key("roomId") references "ROOM"("id") on update NO ACTION on delete NO ACTION;
alter table "SURVEY" add constraint "userFk" foreign key("userId") references "USER"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "SURVEY" drop constraint "roomFk";
alter table "SURVEY" drop constraint "userFk";
drop table "ROOM";
drop table "SURVEY";
drop table "USER";

